<?php

namespace Beekalam\Jdflib\Tests;

use Beekalam\Jdflib\Jdflib;
use PHPUnit\Framework\TestCase;

class JdfLibTest extends TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        require(__DIR__."/jdf.php.original");
    }

    /** @test */
    public function original_gregorian_to_jalali_works_correctly()
    {
        $this->assertEquals(gregorian_to_jalali(1, 1, 2000), Jdflib::gregorian_to_jalali(1, 1, 2000));
    }
}
