<?php

namespace Beekalam\Jdflib\Tests;

use Beekalam\Jdflib\Jdflib;
use PHPUnit\Framework\Test;
use PHPUnit\Framework\TestCase;

class JdfLibTest extends TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        include_once(__DIR__."/jdf.php.original");
    }

    /** @test */
    public function original_gregorian_to_jalali_works_correctly()
    {
        $this->assertEquals(gregorian_to_jalali(1, 1, 2000), Jdflib::gregorian_to_jalali(1, 1, 2000));
    }

    /** @test */
    function given_invalid_date_should_throw_exception_when_wrong_year_is_given_converting_with_convert_jalali_to_gregorian(
    )
    {
        $this->expectException(\InvalidArgumentException::class);

        Jdflib::convert_jalali_to_gregorian("-1/11/11");
    }

    /** @test */
    function given_invalid_date_should_throw_exception_when_wrong_month_is_given_converting_with_convert_jalali_to_gregorian(
    )
    {
        $this->expectException(\InvalidArgumentException::class);

        Jdflib::convert_jalali_to_gregorian("1399/811/11");
    }

    /** @test */
    function given_invalid_date_should_throw_exception_when_wrong_day_is_given_converting_with_convert_jalali_to_gregorian(
    )
    {
        $this->expectException(\InvalidArgumentException::class);

        Jdflib::convert_jalali_to_gregorian("1399/11/99");
    }

    /** @test */
    function should_pad_with_zero_the_date_parts_if_given_the_flag_to_pad_with_zero()
    {
        $ret = Jdflib::convert_jalali_to_gregorian("1399/10/12", "/", "/", true);
        $expected = "2021/01/01";
        $this->assertEquals($expected, $ret);
    }

    /** @test */
    function can_convert_gregorian_to_jalali()
    {
        $expected = Jdflib::gregorian_to_jalali(2000, 1, 1, '-');

        $this->assertEquals($expected, Jdflib::convert_gregorian_to_jalali("2000/1/1", "/", "-"));
    }

    /** @test */
    function can_add_days_to_jalali_date()
    {
        $today = Jdflib::gregorian_to_jalali(2000,1,1,'-'); // 1378-10-11
        $tomorrow = Jdflib::gregorian_to_jalali(2000,1,2,'-'); // 1378-10-12

        $this->assertEquals($tomorrow, Jdflib::add_day($today,1,"-","-"));
    }

    /** @test */
    function can_subtract_days_to_jalali_date()
    {
        $today = Jdflib::gregorian_to_jalali(2000,1,2,'-'); // 1378-10-12
        $tomorrow = Jdflib::gregorian_to_jalali(2000,1,1,'-'); // 1378-10-11

        $this->assertEquals($tomorrow, Jdflib::sub_day($today,1,"-","-"));
    }
}

